CoSign/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cosign/', include("cosign.urls")), # cosign project url domain
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoSign/cosign/urls.py
# cosign/urls.py

from django.urls import path
from .views import *
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth import views as auth_views # generic view for auth


#       urlpatterns is an array or path functions that
#   contain all url destinations within the cosign
#   application

#           path('url', ViewComponent, name='name')

#       The first parameter in the path function is the url
#   pattern, this is what you put in the url after the project
#   domain (e.g. cosign/url). The second parameter is a view components,
#   which is a component that contains the logic to display the html and required
#   context for the page. The last parameter is the name which like a nickname that
#   represents the url pattern in the rest of the django project.

urlpatterns = [

    # Profiles
    path('', RedirectView.as_view(url="show_all_profiles", permanent=False), name='home'), # redirects a user to CoSign's home page url pattern
    path('show_all_profiles', ShowAllProfiles.as_view(), name='show_all_profiles'),
    path('profile/<int:pk>', ProfileDetailView.as_view(), name='show_profile'),
    path('profile/<int:pk>/update', ProfileUpdateView.as_view(), name='update_profile'),
    # path('profile/<int:pk>/delete', ProfileDeleteView.as_view(), name='delete_profile'),



    # Post and Feed

    # Interactions

    #

]

CoSign/cosign/models.py
from django.db import models

# Create your models here.

#           A model is the single, definitive source of information 
#       about your data. They contain the essential fields and 
#       behaviors of the data you’re storing. In general, each model maps 
#       to a single database table.

class Profile(models.Model):
    '''
    Data definition for the Profile model.
    
    models
        :username: = models.TextField(max_length=20, unique=True)
        :name: = models.TextField(blank=True)
        :pfp_file: = models.FileField(blank=True, null=True)
        :bio: = models.TextField(blank=True)
        :pfp_file: = models.ImageField(blank=True, null=True, default="defaultpfp.jpg")
        :created: = models.DateTimeField(auto_now_add=True, blank=True)


    '''
    # user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    username = models.TextField(max_length=20, unique=True)
    first_name = models.TextField(blank=True)
    last_name = models.TextField(blank=True)
    pfp_file = models.ImageField(blank=True, null=True)
    bio = models.TextField(blank=True)

    created = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return f'{self.username}'


class Post(models.Model):
    '''
    Data definition for the Post model.

    models
        :profile: = models.ForeignKey(Profile, on_delete=models.CASCADE)
        :caption: = models.TextField(max_length=100, blank=True)
        :created: = models.DateTimeField(auto_now_add=True, blank=True)

    '''

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    caption = models.TextField(max_length=100, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)

    # The max date a post can apear on the public feed, 14 days
    # after a post's first cosign
    max_feed_date = models.DateField(blank=True) 


class Image(models.Model):
    '''Data definition for the Image model.

    models
        :post: = models.ForeignKey(Post, on_delete=models.CASCADE)
        :image: = models.FileField(blank=True, null=True)
        :created: = models.DateTimeField(auto_now_add=True, blank=True)


    '''

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.FileField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)


class CoSign(models.Model):
    '''
    Data definition for the CoSign model. 

    models
        :post: = models.ForeignKey(Post, on_delete=models.CASCADE)
        :profile: = models.ForeignKey(Profile, on_delete=models.CASCADE)
        :created: = models.DateTimeField(auto_now_add=True, blank=True)

    functions
        :def can_go_to_feed(self): returns True if post can go to public feed
    '''

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    
    created = models.DateTimeField(auto_now_add=True, blank=True)

    def can_go_to_feed(self):
        '''
        Docstring for can_go_to_feed
        
        :param self: The CoSign Object calling the function

        :return True: If the date is before the maximum date the
            post is allowed to be on the public feed 
        '''

        if self.date > self.post.max_feed_date:
            return False
        else:
            return True



class Like(models.Model):
    '''
    Data definition for the Like model. 

    post = models.ForeignKey(Post, on_delete=models.CASCADE) \n
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE) \n
    
    created = models.DateTimeField(auto_now_add=True, blank=True)
    
    '''

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True, blank=True)



class Comment(models.Model):
    '''
    Data definition for the Comment model. 

    post = models.ForeignKey(Post, on_delete=models.CASCADE) \n
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE) \n
    comment = models.TextField(max_length=100) \n
    
    created = models.DateTimeField(auto_now_add=True, blank=True)
    
    '''

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    comment = models.TextField(max_length=100)

    created = models.DateTimeField(auto_now_add=True, blank=True)

CoSign/cosign/forms.py
# cosign/forms.py

from django import forms
from .models import *

#       Forms are 

class CreateProfileForm(forms.ModelForm):
    '''form to create a profile'''

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'username',
            'bio',
            'pfp_file'
        ]

class UpdateProfileForm(forms.ModelForm):
    '''form to update a profile'''

    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'username',
            'bio',
            'pfp_file'
        ]

CoSign/cosign/views.py
# cosign/views.py

from .forms import *
from .models import *

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import redirect
from django.urls import reverse

from django.views.generic import \
    View,       \
    ListView,   \
    DetailView, \
    CreateView, \
    UpdateView, \
    DeleteView

# Create your views here.

#       Views are the foundational components that structure
#   the project's user experience logic. These control what the 
#   user



# =============================================
#       Temporary View for easy access to 
#       setup and test views
#
#           - ShowAllProfiles
#
# =============================================

class ShowAllProfiles(ListView):

    model = Profile
    template_name = 'cosign/show_all_profiles.html'
    context_object_name = 'profiles'



# =============================================
#                  Profile
#
#           - ProfileDetailView
#           - ProfileCreateView
#           - ProfileUpdateView
#           - ProfileDeleteView
#           - ShowFollowersDetailView
#           - ShowFollowingDetailView
#
# =============================================

class ProfileDetailView(DetailView):
    '''Class definition for Profile page'''

    model = Profile
    template_name = 'cosign/profile/show_profile.html'

    def get_context_data(self, **kwargs):
        '''Gets context data for a page'''

        context = super().get_context_data(**kwargs)

        pk = self.kwargs['pk']
        profile = Profile.objects.get(pk=pk)
        context['profile'] = profile

        return context
    



# class ProfileCreateView(CreateView):

#     model = Profile
#     form_class = CreateProfileForm
#     template_name = 'cosign/profile/create_profile'

#     def get_context_data(self, **kwargs):
#         '''provides context data for the create view'''

#         context = super().get_context_data()

#         if self.request.method == 'POST':
#             userForm = UserCreationForm(self.request.POST)
#             profileForm = CreateProfileForm(self.request.POST, self.request.FILES)
#         else:
#             userForm = UserCreationForm()
#             profileForm = CreateProfileForm()
        
#         context['userForm'] = userForm
#         context['profileForm'] = profileForm

#         return context

#     def form_valid(self, form):
#         '''Submits a new profile object to the database given and valid creation form'''

#         userForm = UserCreationForm(self.request.POST)

#         if userForm.is_valid():
#             user = userForm.save()
#             login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
#             form.instance.user = user

#         return super().form_valid(form)
    
#     def get_success_url(self):
#         '''returns ProfileDetailView's after successful profile update'''

#         return reverse("show_profile", kwargs={"pk": self.object.pk})



class ProfileUpdateView(UpdateView):
    '''View that displays the page to update a profile'''


    model = Profile
    form_class = UpdateProfileForm
    template_name = 'cosign/profile/update_profile.html'
    context_object_name = 'profile'

    def get_success_url(self):
        '''returns ProfileDetailView's after successful profile update'''

        return reverse("show_profile", kwargs={"pk": self.object.pk})
    
    def get_context_data(self, **kwargs):
        '''provides context data for update view'''

        context = super().get_context_data()

        pk = self.kwargs['pk']
        profile = Profile.objects.get(pk=pk)
        context['profile'] = profile

        return context


#        IMPLEMENT LOGINREQUIREDMIXIN BEFORE DELETE VIEW

# class ProfileDeleteView(DeleteView):

#     model = Profile
#     template_name = 'cosign/profile/update_profile'

    
#     def get_context_data(self, **kwargs):
#         '''provides context data for update view'''

#         context = super().get_context_data()

#         pk = self.kwargs['pk']
#         profile = Profile.objects.get(pk=pk)
#         context['profile'] = profile

#         return context
    
#     def get_success_url(self):
#         '''returns ProfileDetailView's after successful profile update'''

#         return reverse("show_all_profiles")
    
    




# =============================================
#                   Feed
#
#           - CoSignFeedView
#           - PrivateFeedView
#           - SearchView
#
# =============================================



# =============================================
#                   Post
#
#           - PostDetailView
#           - PostCreateView
#           - PostUpdateView
#           - PostDeleteView
#
# =============================================






# =============================================
#               Interactions
#           
#           - CosignView
#           - LikeView
#           - FollowView
# 
# =============================================

CoSign/cosign/templates/cosign/profile/create_profile.html
<!-- cosign/templates/cosign/profile/create_profile.html -->


{% extends 'cosign/base.html' %}

{% block content %}


<h1 id="titleCreateProfile">Create Profile</h1>
<div id="container">
    <form action="{% url 'create_profile' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <fieldset class="fieldset">
            <legend class="legend">Login Information</legend>
            
            <table>
                <div class="form-group">
                    <label for="id_first_name">First name</label>
                    {{ profileForm.first_name }}
                </div>

                <div class="form-group">
                    <label for="id_last_name">Last name</label>
                    {{ profileForm.last_name }}
                </div>

                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ profileForm.email }}
                </div>

                <div class="form-group">
                    <label for="id_username">Username</label>
                    {{ userForm.username }}
                </div>
                
                <div class="form-group">
                    <label for="id_password">Password</label>
                    {{ userForm.password1 }}
                     <small class="helptext">
                        {{ userForm.password1.help_text|safe }}
                    </small>
                </div>
                
                <div class="form-group">
                    <label for="id_password_confirmation">Password Confirmation</label>
                    {{ userForm.password2 }}
                </div>

            </table>
        </fieldset>
        <br><br>
        <fieldset class="fieldset">
            
            <legend class="legend">Profile Customization</legend>
                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ profileForm.city }}
                </div>

                <div class="form-group">
                    <label for="id_state">State</label>
                    {{ profileForm.state }}
                </div>

                <div class="form-group">
                    <label for="id_zip_code">Zip Code</label>
                    {{ profileForm.zip_code }}
                </div>

                <div class="form-group">
                    <label for="id_profile_image">Profile Image</label>
                    {{ profileForm.profile_image }}
                </div>

                <div class="form-group">
                    <label for="id_bio">Bio</label>
                    {{ profileForm.bio }}
                </div>

        </fieldset>

            
        <div class="button-container">
            <input type="submit" name="submit" class="submit-button">
            <a href="{% url 'market' %}" class="cancel-button">cancel</a>
        </div>
    </form>
</div>


{% endblock %}

CoSign/cosign/templates/cosign/profile/show_profile.html
<!-- cosign/templates/profile/show_profile.html -->

{% extends 'cosign/base.html' %}
{% load static %}

{% block sub_css %}
<link rel="stylesheet" href="{% static 'cosign/css/profile/show_profile-styles.css' %}">
{% endblock sub_css %}

{% block content %}
<div class="profilePage">
    <section class="profileHeader">
        <div class="profileHeader-main">
            {% if profile.pfp_file %}
                <img src="{{ profile.pfp_file.url }}" alt="Profile picture" class="profileAvatar">
            {% else %}
                <img src="{% static 'cosign/img/defaultpfp.jpg' %}" alt="profile picture" class="profileAvatar">
            {% endif %}
            <div>
                <h1 class="profileName">
                    {{ profile.first_name }} {{ profile.last_name }}
                </h1>
                <p class="profileHandle">@{{ profile.username }}</p>
            </div>
        </div>
        <div class="profile-bio">
            {{ profile.bio }}
        </div>
        <div class="buttonBox">
            <div class="updateButton">
                <a href="{% url 'update_profile' profile.pk %}">Update</a>
            </div>
            <div class="deleteButton">
                <p>Delete</p>
            </div>
        </div>
    </section>
</div>

{% endblock content %}

CoSign/cosign/templates/cosign/profile/update_profile.html
<!-- /cosign/templates/cosign/profile/update_profile.html -->

{% extends 'cosign/base.html' %}
{% load static %}

{% block sub_css %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
{% endblock sub_css %}

{% block content %}

<h1>{{ profile.username }}: Update Profile</h1>
<div>
    <form action="{% url 'update_profile' profile.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" value="{{ profile.username|default:'' }}">
        </div>
        
        <div class="mb-3">
            <label for="username" class="form-label">First Name</label>
            <input type="text" class="form-control" id="username" value="{{ profile.first_name|default:'' }}">
        </div>

        <div class="mb-3">
            <label for="username" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="username" value="{{ profile.last_name|default:'' }}">
        </div>

        <div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="button" onclick=""></button>
        </div>

    </form>
</div>

{% endblock %}